spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        ddl-auto: create
        default_batch_fetch_size: 100

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql: trace
        orm.jdbc.bind: trace

auth:
  jwt:
    issuer: team.sparta.com
    secret: fd56781c74b54b04a0f1482ca6cb056e2716429595ff7838065c336f47036860
    accessTokenExpirationHour: 1
    refreshTokenExpirationHour: 168